name: "NIST Opensource Portal"
author: "NIST Open Source <opensource@nist.gov>"
title: NIST Opensource Portal
description: "National Institute of Standards Opensource Portal"
remote_theme: usnistgov/Opensource-Theme

url: "https://opensource.nist.gov"
repo_url: "https://github.com/usnistgov/opensource"

# LLNL Piwik Analytics https://analytics.llnl.gov
# piwik_id: 250

# Google Analytics ID
# google_analytics:
#  tracking_id: UA-75179431-1

# Twitter username (used by jekyll-seo-tag)
# twitter:
#  username: llnl_opensource

# GitHub Metadata -- https://github.com/jekyll/github-metadata
repository: usnistgov/opensource
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

kramdown:
  auto_ids: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/news/:year/:month/:day/:title/"

permalink: pretty

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - README.md
    - Makefile
    - build

theme: jekyll-theme-cayman
